// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNdPmeAHJF08Ok1iDe56ZKmleTlFbXGs',
    appId: '1:787914014083:web:f7dedbb5e52a090a62cab6',
    messagingSenderId: '787914014083',
    projectId: 'mynotes-c58ab',
    authDomain: 'mynotes-c58ab.firebaseapp.com',
    storageBucket: 'mynotes-c58ab.firebasestorage.app',
    measurementId: 'G-F3MV3N26CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZRGuQJ3LqzDmm_v1cPby2IfpQA8cRYY',
    appId: '1:787914014083:android:da1b06a595f8894462cab6',
    messagingSenderId: '787914014083',
    projectId: 'mynotes-c58ab',
    storageBucket: 'mynotes-c58ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3JLg3r6ONxVyO4tCzCLC3-uRKwkITSI',
    appId: '1:787914014083:ios:c3b5079e8d0979dd62cab6',
    messagingSenderId: '787914014083',
    projectId: 'mynotes-c58ab',
    storageBucket: 'mynotes-c58ab.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3JLg3r6ONxVyO4tCzCLC3-uRKwkITSI',
    appId: '1:787914014083:ios:c3b5079e8d0979dd62cab6',
    messagingSenderId: '787914014083',
    projectId: 'mynotes-c58ab',
    storageBucket: 'mynotes-c58ab.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUNdPmeAHJF08Ok1iDe56ZKmleTlFbXGs',
    appId: '1:787914014083:web:81227f73793c25b962cab6',
    messagingSenderId: '787914014083',
    projectId: 'mynotes-c58ab',
    authDomain: 'mynotes-c58ab.firebaseapp.com',
    storageBucket: 'mynotes-c58ab.firebasestorage.app',
    measurementId: 'G-4XTMD2NB54',
  );

}